config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'static_pages#home'
  get 'johnochs', to: 'static_pages#johnochs'
  get 'learnmore', to: 'static_pages#learnmore'
  
  namespace :api, defaults: { format: :json} do
    resources :tracks, only: [:create, :update, :index, :show, :destroy]
    resources :tracksearch, only: [:index]
    resource :neojson, only: [:show]
    resources :users, only: [:index, :show, :update, :destroy]
    resource :session, only: [:create, :destroy]
    resources :relationships, only: [:show, :update, :destroy]
  end
  
  
  resources :users, only: [:create, :new, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :stats, only: [:index]

end

app/models/added_by.rb
class AddedBy
  include Neo4j::ActiveRel
  
  from_class User
  to_class Track
  
  type 'ADDED'
end

app/models/artist.rb
class Artist
  include Neo4j::ActiveNode
  property :name
  property :spotify_uri
  
  index :spotify_uri
end

app/models/comment.rb
class Comment
  include Neo4j::ActiveNode
  property :title
  property :text
  
  index :title
  has_one :out, :track, type: :track, model_class: Track
end

app/models/covers.rb
class Covers
  include Neo4j::ActiveRel
  
  from_class Track
  to_class Track
  type 'COVERS'
  
  property :notes
  property :contest_count
  property :created_at
  property :updated_at
  property :added_by
end

app/models/remixes.rb
class Remixes
  include Neo4j::ActiveRel
  
  from_class Track
  to_class Track
  type 'REMIXES'
  
  property :notes
  property :contest_count
  property :created_at
  property :upated_at
  property :added_by
end

app/models/samples.rb
class Samples
  include Neo4j::ActiveRel
  
  from_class Track
  to_class Track
  type 'SAMPLES'
  
  property :sample_type
  property :added_by
  property :notes
  property :significance, type: Integer
  property :child_url
  property :parent_url
  property :child_start_time
  property :parent_start_time
  property :contest_count
  property :created_at
  property :updated_at
end

app/models/track.rb
class Track
  include Neo4j::ActiveNode
  
  id_property :spot_id, on: :DBID
  
  property :track_spotify_id
  property :track_name
  property :track_number
  property :track_preview_url
  property :track_spotify_uri
  property :track_popularity
  property :track_href
  property :track_external_url
  property :track_duration_ms
  property :artist_name
  property :artist_spotify_id
  property :artist_spotify_href
  property :artist_href
  property :album_name
  property :album_spotify_id
  property :album_spotify_uri
  property :album_l_image
  property :album_m_image
  property :album_s_image
  property :album_href
  property :created_at
  property :updated_at
  
  validates :track_name, :track_spotify_id, presence: true
  
  index :track_spotify_id
  
  has_many :out, :samples, model_class: Track
  has_many :out, :covers, model_class: Track
  has_many :out, :remixes, model_class: Track
  
  has_many :in, :sampled_by, model_class: Track, origin: :samples
  has_many :in, :covered_by, model_class: Track, origin: :covers
  has_many :in, :remixed_by, model_class: Track, origin: :remixes
  
  def DBID
    self.track_spotify_id
  end
  
  def self.find_by_spotify_id(id)
    @track = Track.where(track_spotify_id: id).first
  end

end

app/models/user.rb
class User
  include Neo4j::ActiveNode
  
  before_validation :ensure_token
  before_save :ensure_password_confirmation
  
  property :username, index: :exact, constraint: :unique
  property :pwdigest
  property :session_token, index: :exact, constraint: :unique
  property :email, constraint: :unique
  property :img_url
  property :fname
  property :lname
  property :location
  property :created_at
  property :updated_at
  
  validates :username, :session_token, presence: true
  validates :username, :email, :session_token, uniqueness: true
  validates :pwdigest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  
  attr_reader :password, :password_confirmation
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.valid_password?(password) ? user : nil
  end
  
  def reset_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save
    self.session_token
  end
  
  def password_confirmation=(password_confirmation)
    @password_confirmation = password_confirmation
  end
  
  def password=(password)
    @password = password
    self.pwdigest = BCrypt::Password.create(password)
  end
  
  def valid_password?(password)
    BCrypt::Password.new(self.pwdigest).is_password?(password)
  end
  
  private
  
  def ensure_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end
  
  def ensure_password_confirmation
    if self.persisted?
      return true
    else
      self.password == self.password_confirmation
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
    
    render "new"
  end
  
  def create
    @user = User.find_by_credentials(
      user_params[:username],
      user_params[:password]
    )
    
    if @user
      login!(@user)
      redirect_to "http://www.beat-tree.com/#feed"
    else
      flash[:errors] = ["Invalid Username or Password"]
      render "new"
    end
    
  end
  
  def destroy
    logout!
    redirect_to "http://www.beat-tree.com"
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
  
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  
  def index
    @numtracks = Neo4j::Session.query("MATCH (n:Track) RETURN count(n) AS tracks").first.tracks
    @numusers = Neo4j::Session.query("MATCH (n:User) RETURN count(n) AS users").first.users
    @relationships = Neo4j::Session.query("MATCH ()-[r]->() RETURN count(r) AS relationships").first.relationships
    @most_sampled = Track.query_as(:t).match("t<-[r:SAMPLES]-()").return("t, count(r) AS count").order_by("count DESC").limit(5)
    render "index", status: :ok
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
    
    render 'new'
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      login!(@user)
      redirect_to "http://www.beat-tree.com/#welcome"
    else
      puts @user.errors.full_messages
      flash[:errors] = @user.errors.full_messages
      render 'new'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password, :email, :fname, :lname, :location, :img_url, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/neo_json_helper.rb
module NeoJsonHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/tracksearch_helper.rb
module TracksearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeatTree</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <script>BT.current_user=
  <% if logged_in? %>
  "<%= current_user.username %>";
  <% else %>
  <%= "null" %>;
  <% end %>
  </script>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-58696295-1', 'auto');
	  ga('send', 'pageview');

	</script>
</head>
  
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container-fluid">
		<ul class="nav navbar-nav nabvar-left">
			<li class="first-left">
		      <a class="navbar-brand beat-tree-brand" href="http://www.beat-tree.com/#feed">
		        <img class="navbar-btlogo-img" alt="BeatTree" src="https://s3-us-west-1.amazonaws.com/beat-tree-images/bt-logo.gif">
		      </a>
		    </li>
			<li>
				<div class="beat-tree-header-title">
					BeatTree
				</div>
			</li>
			<% if !logged_in? %>
				<li>
					<%= link_to "Sign Up", new_user_path %>
				</li>
				<li>
					<%= link_to "Log In", new_session_path %>
				</li>
			<% else %>
	            <li><%= button_to "Log Out", session_url, method: :delete, class: 'btn btn-danger log-out-btn'%></li>
	            <li><a href="#/users/<%= current_user.username %>">Logged in as: <%= current_user.username %></a></li>
			<% end %>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li>
				<a data-toggle="collapse" href="#collapse-track-queue">
					<span class="glyphicon glyphicon-collapse-down"></span>
					Show Track Queue
				</a>
			</li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-music"></span> What You're Hearing <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li id="beat-tree-player-viewport">
	            	<img src="https://s3-us-west-1.amazonaws.com/beat-tree-images/info-add-track.gif">
	            </li>
	          </ul>
	       </li>
	    </ul>
	</div>
</nav>
  <div class="container" id="beat-tree-content">
	<%= yield %>
  </div>
  <div class="collapse" id="collapse-track-queue">
	  <nav class="navbar navbar-inverse navbar-fixed-bottom">
		  <div class="row track-queue-container"></div>
	  </nav>
  </div>
  <div class="custom-alert">
	<div id="dialogoverlay"></div>
	<div id="dialogbox">
	  <div>
	    <div id="dialogboxhead">
	    </div>
	    <div id="dialogboxbody"></div>
		<div><ul id="customalertitems"></ul></div>
	    <div id="dialogboxfoot"></div>
	  </div>
	</div>
	</div>
</body>
</html>